local M = {}

--   פּ ﯟ   some other good icons
M.kind_icons = {
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Keyword = " ",
    Method = "m ",
    Module = " ",
    Operator = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
}
-- find more here: https://www.nerdfonts.com/cheat-sheet

-- from https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/icons.lua
M.nvchad_icons = {
    -- Class = "ﴯ",
    -- Constant = "",
    -- EnumMember = "了",
    -- Text = "",
    -- TypeParameter = "",
    -- Variable = "",
    -- Variable = "",
    Array = "[]",
    Boolean = "",
    Calendar = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "了",
    EnumMember = "",
    Event = "",
    Field = "ﰠ",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "ﳠ",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "ﰠ",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "פּ",
    Table = "",
    Tag = "",
    Text = "",
    TypeParameter = "",
    Unit = "塞",
    Value = "",
    Variable = "",
    Watch = "",
}

M.nyoom_icons = {
    Class = "  ",
    Color = "  ",
    Constant = "  ",
    Constructor = "  ",
    Copilot = "  ",
    Enum = "  ",
    EnumMember = "  ",
    Event = "  ",
    Field = "  ",
    File = "  ",
    Folder = "  ",
    Function = "  ",
    Interface = "  ",
    Keyword = "  ",
    Method = "  ",
    Module = "  ",
    Operator = "  ",
    Property = "  ",
    Reference = "  ",
    Snippet = "  ",
    Struct = "  ",
    Text = "  ",
    TypeParameter = "  ",
    Unit = "  ",
    Value = "  ",
    Variable = "  ",
}

return M
