local M = {}

--   פּ ﯟ   some other good icons
M.kind_icons = {
    Text = " ",
    Method = "m ",
    Function = " ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
}
-- find more here: https://www.nerdfonts.com/cheat-sheet

-- from https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/icons.lua
M.nvchad_icons = {
    Namespace = "",
    -- Text = "",
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "ﰠ",
    -- Variable = "",
    -- Variable = "",
    Variable = "",
    -- Class = "ﴯ",
    Class = "",
    Interface = "",
    Module = "",
    Property = "ﰠ",
    Unit = "塞",
    Value = "",
    Enum = "了",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    -- EnumMember = "了",
    EnumMember = "",
    -- Constant = "",
    Constant = "",
    Struct = "פּ",
    Event = "",
    Operator = "",
    -- TypeParameter = "",
    TypeParameter = "",
    Table = "",
    Object = "",
    Tag = "",
    Array = "[]",
    Boolean = "",
    Number = "",
    Null = "ﳠ",
    String = "",
    Calendar = "",
    Watch = "",
    Package = "",
}

return M
