local M = {}

local opts = { noremap = true, silent = true }
M.opts_and_desc = function(msg)
    return vim.tbl_deep_extend("force", opts, { desc = msg })
end

--   פּ ﯟ   some other good icons
M.kind_icons = {
    Class = "󰌗 ",
    Color = "󰏘 ",
    Constant = "󰇽 ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = "󰈙 ",
    Folder = "󰉋 ",
    Function = "󰊕 ",
    Interface = " ",
    Keyword = "󰌋 ",
    Method = "m ",
    Module = " ",
    Operator = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    Struct = " ",
    Text = "󰉿 ",
    TypeParameter = "󰊄 ",
    Unit = " ",
    Value = "󰎠 ",
    Variable = "󰆧 ",
}
-- find more here: https://www.nerdfonts.com/cheat-sheet

-- from https://github.com/NvChad/ui/blob/main/lua/nvchad_ui/icons.lua
M.nvchad_icons = {
    -- Class = "󰠱",
    -- Constant = "󰏿",
    -- EnumMember = "󰒻",
    -- Text = "󰉿",
    -- TypeParameter = "󰊄",
    -- Variable = "",
    -- Variable = "󰂡",
    Array = "[]",
    Boolean = "",
    Calendar = "",
    Class = "",
    Color = "󰏘",
    Constant = "",
    Constructor = "",
    -- Enum = "󰒻",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "󰜢",
    File = "󰈙",
    Folder = "󰉋",
    Function = "󰆧",
    Interface = "",
    Keyword = "󰌋",
    Method = "󰆧",
    Module = "",
    Namespace = "󰌗",
    Null = "󰟢",
    Number = "",
    Object = "󰅩",
    Operator = "󰆕",
    Package = "",
    Property = "󰜢",
    Reference = "󰈇",
    Snippet = "",
    String = "󰉿",
    Struct = "󰙅",
    Table = "",
    Tag = "",
    Text = "",
    TypeParameter = "",
    Unit = "󰑭",
    Value = "󰎠",
    Variable = "",
    Watch = "󰥔",
}

M.nyoom_icons = {
    Class = "  ",
    Color = "  ",
    Constant = "  ",
    Constructor = "  ",
    Copilot = "  ",
    Enum = "  ",
    EnumMember = "  ",
    Event = "  ",
    Field = "  ",
    File = "  ",
    Folder = "  ",
    Function = "  ",
    Interface = "  ",
    Keyword = "  ",
    Method = "  ",
    Module = "  ",
    Operator = "  ",
    Property = "  ",
    Reference = "  ",
    Snippet = "  ",
    Struct = "  ",
    Text = "  ",
    TypeParameter = "  ",
    Unit = "  ",
    Value = "  ",
    Variable = "  ",
}

return M
