return {
  opts = {
    indent = {
      char = "│",
      tab_char = "│",
    },
    scope = {
      enabled = true,
      show_start = true,
      show_end = false,
      include = {
        node_type = {
          ["*"] = {
            "argument_list",
            "arguments",
            "assignment_statement",
            "Block",
            "chunk",
            "class",
            "ContainerDecl",
            "dictionary",
            "do_block",
            "do_statement",
            "element",
            "except",
            "FnCallArguments",
            "for",
            "for_statement",
            "function",
            "function_declaration",
            "function_definition",
            "if_statement",
            "IfExpr",
            "IfStatement",
            "import",
            "InitList",
            "jsx_self_closing_element",
            "list_literal",
            "method",
            "object",
            "ParamDeclList",
            "repeat_statement",
            "return_statement",
            "selector",
            "SwitchExpr",
            "table",
            "table_constructor",
            "try",
            "tuple",
            "type",
            "var",
            "while",
            "while_statement",
            "with",
          },
        },
      },
    },
    whitespace = {
      remove_blankline_trail = true,
    },
    exclude = {
      filetypes = {
        "",
        "alpha",
        "dashboard",
        "NvimTree",
        "help",
        "markdown",
        "dirvish",
        "nnn",
        "packer",
        "toggleterm",
        "lsp-installer",
        "Outline",
      },
    },
  },
}
