local M = {}

M.ensure_installed = {
  "astro-language-server",
  "bash-language-server",
  "clangd",
  "codelldb",
  "css-lsp",
  "cssmodules-language-server",
  -- "emmet-ls",
  "flake8",
  "gofumpt",
  "goimports",
  "gopls",
  "html-lsp",
  "jdtls",
  "json-lsp",
  "julia-lsp",
  "lua-language-server",
  "prettier",
  "pyright",
  "r-languageserver",
  "ruff",
  "rust-analyzer",
  "shfmt",
  "sqlfluff",
  "sqlls",
  "stylelint-lsp",
  "stylua",
  "svelte-language-server",
  "tailwindcss-language-server",
  "texlab",
  "tinymist",
  "vim-language-server",
  "vtsls",
  -- "typescript-language-server",
  "vue-language-server",
  "zk",
  "zls",
}

-- Initially obtained with:
-- require("mason-lspconfig").get_mappings().package_to_lspconfig
M.names_mapping = {
  air = "air",
  ["angular-language-server"] = "angularls",
  ["ansible-language-server"] = "ansiblels",
  ["antlers-language-server"] = "antlersls",
  ["arduino-language-server"] = "arduino_language_server",
  ["asm-lsp"] = "asm_lsp",
  ["ast-grep"] = "ast_grep",
  ["astro-language-server"] = "astro",
  ["autotools-language-server"] = "autotools_ls",
  ["awk-language-server"] = "awk_ls",
  ["azure-pipelines-language-server"] = "azure_pipelines_ls",
  basedpyright = "basedpyright",
  ["bash-language-server"] = "bashls",
  ["bazelrc-lsp"] = "bazelrc_lsp",
  ["beancount-language-server"] = "beancount",
  ["bicep-lsp"] = "bicep",
  biome = "biome",
  brighterscript = "bright_script",
  ["bsl-language-server"] = "bsl_ls",
  buf = "buf_ls",
  bzl = "bzl",
  ["cairo-language-server"] = "cairo_ls",
  clangd = "clangd",
  ["clarity-lsp"] = "clarity_lsp",
  ["clojure-lsp"] = "clojure_lsp",
  ["cmake-language-server"] = "cmake",
  ["cobol-language-support"] = "cobol_ls",
  codeql = "codeqlls",
  ["coq-lsp"] = "coq_lsp",
  crystalline = "crystalline",
  ["csharp-language-server"] = "csharp_ls",
  ["css-lsp"] = "cssls",
  ["css-variables-language-server"] = "css_variables",
  ["cssmodules-language-server"] = "cssmodules_ls",
  ["cucumber-language-server"] = "cucumber_language_server",
  cuelsp = "dagger",
  ["custom-elements-languageserver"] = "custom_elements_ls",
  ["cypher-language-server"] = "cypher_ls",
  deno = "denols",
  ["dhall-lsp"] = "dhall_lsp_server",
  ["diagnostic-languageserver"] = "diagnosticls",
  ["docker-compose-language-service"] = "docker_compose_language_service",
  ["dockerfile-language-server"] = "dockerls",
  ["dot-language-server"] = "dotls",
  dprint = "dprint",
  earthlyls = "earthlyls",
  efm = "efm",
  ["elixir-ls"] = "elixirls",
  ["elm-language-server"] = "elmls",
  elp = "elp",
  ["ember-language-server"] = "ember",
  ["emmet-language-server"] = "emmet_language_server",
  ["emmet-ls"] = "emmet_ls",
  emmylua_ls = "emmylua_ls",
  ["erg-language-server"] = "erg_language_server",
  ["erlang-ls"] = "erlangls",
  esbonio = "esbonio",
  ["eslint-lsp"] = "eslint",
  ["facility-language-server"] = "facility_language_server",
  ["fennel-language-server"] = "fennel_language_server",
  ["fennel-ls"] = "fennel_ls",
  ["flux-lsp"] = "flux_lsp",
  ["foam-language-server"] = "foam_ls",
  fortls = "fortls",
  fsautocomplete = "fsautocomplete",
  ["gh-actions-language-server"] = "gh_actions_ls",
  ginko_ls = "ginko_ls",
  ["gitlab-ci-ls"] = "gitlab_ci_ls",
  glint = "glint",
  glsl_analyzer = "glsl_analyzer",
  glslls = "glslls",
  ["golangci-lint-langserver"] = "golangci_lint_ls",
  gopls = "gopls",
  ["gradle-language-server"] = "gradle_ls",
  ["grammarly-languageserver"] = "grammarly",
  ["graphql-language-service-cli"] = "graphql",
  ["groovy-language-server"] = "groovyls",
  ["harper-ls"] = "harper_ls",
  ["haskell-language-server"] = "hls",
  ["haxe-language-server"] = "haxe_language_server",
  ["hdl-checker"] = "hdl_checker",
  ["helm-ls"] = "helm_ls",
  ["hoon-language-server"] = "hoon_ls",
  ["html-lsp"] = "html",
  ["htmx-lsp"] = "htmx",
  ["hydra-lsp"] = "hydra_lsp",
  hyprls = "hyprls",
  intelephense = "intelephense",
  ["java-language-server"] = "java_language_server",
  jdtls = "jdtls",
  ["jedi-language-server"] = "jedi_language_server",
  ["jinja-lsp"] = "jinja_lsp",
  ["jq-lsp"] = "jqls",
  ["json-lsp"] = "jsonls",
  ["jsonnet-language-server"] = "jsonnet_ls",
  ["julia-lsp"] = "julials",
  ["just-lsp"] = "just",
  kcl = "kcl",
  ["kotlin-language-server"] = "kotlin_language_server",
  lelwel = "lelwel_ls",
  lemminx = "lemminx",
  lexical = "lexical",
  ["ltex-ls"] = "ltex",
  ["ltex-ls-plus"] = "ltex_plus",
  ["lua-language-server"] = "lua_ls",
  ["luau-lsp"] = "luau_lsp",
  ["lwc-language-server"] = "lwc_ls",
  ["markdown-oxide"] = "markdown_oxide",
  marksman = "marksman",
  ["matlab-language-server"] = "matlab_ls",
  ["mdx-analyzer"] = "mdx_analyzer",
  mesonlsp = "mesonlsp",
  ["metamath-zero-lsp"] = "mm0_ls",
  millet = "millet",
  ["motoko-lsp"] = "motoko_lsp",
  ["move-analyzer"] = "move_analyzer",
  ["mutt-language-server"] = "mutt_ls",
  neocmakelsp = "neocmake",
  ["nextflow-language-server"] = "nextflow_ls",
  nextls = "nextls",
  ["nginx-language-server"] = "nginx_language_server",
  ["nickel-lang-lsp"] = "nickel_ls",
  ["nil"] = "nil_ls",
  nimlangserver = "nim_langserver",
  nimlsp = "nimls",
  ["nomicfoundation-solidity-language-server"] = "solidity_ls_nomicfoundation",
  ["ocaml-lsp"] = "ocamllsp",
  ols = "ols",
  omnisharp = "omnisharp",
  ["omnisharp-mono"] = "omnisharp_mono",
  ["opencl-language-server"] = "opencl_ls",
  ["openscad-lsp"] = "openscad_lsp",
  oxlint = "oxlint",
  pbls = "pbls",
  perlnavigator = "perlnavigator",
  ["pest-language-server"] = "pest_ls",
  phpactor = "phpactor",
  ["pico8-ls"] = "pico8_ls",
  ["pkgbuild-language-server"] = "pkgbuild_language_server",
  postgrestools = "postgres_lsp",
  ["powershell-editor-services"] = "powershell_es",
  ["prisma-language-server"] = "prismals",
  ["prosemd-lsp"] = "prosemd_lsp",
  protols = "protols",
  psalm = "psalm",
  ["puppet-editor-services"] = "puppet",
  ["purescript-language-server"] = "purescriptls",
  pylyzer = "pylyzer",
  pyre = "pyre",
  pyright = "pyright",
  ["python-lsp-server"] = "pylsp",
  ["quick-lint-js"] = "quick_lint_js",
  ["r-languageserver"] = "r_language_server",
  ["raku-navigator"] = "raku_navigator",
  ["reason-language-server"] = "reason_ls",
  regal = "regal",
  regols = "regols",
  ["remark-language-server"] = "remark_ls",
  ["rescript-language-server"] = "rescriptls",
  ["rnix-lsp"] = "rnix",
  ["robotframework-lsp"] = "robotframework_ls",
  rome = "rome",
  rubocop = "rubocop",
  ["ruby-lsp"] = "ruby_lsp",
  ruff = "ruff",
  ["rust-analyzer"] = "rust_analyzer",
  rust_hdl = "vhdl_ls",
  ["salt-lsp"] = "salt_ls",
  ["serve-d"] = "serve_d",
  ["shopify-cli"] = "shopify_theme_ls",
  ["shopify-theme-check"] = "theme_check",
  slang = "slangd",
  ["slint-lsp"] = "slint_lsp",
  ["smithy-language-server"] = "smithy_ls",
  ["snakeskin-cli"] = "snakeskin_ls",
  ["snyk-ls"] = "snyk_ls",
  solang = "solang",
  solargraph = "solargraph",
  solidity = "solc",
  ["solidity-ls"] = "solidity",
  ["some-sass-language-server"] = "somesass_ls",
  sorbet = "sorbet",
  sourcery = "sourcery",
  ["spectral-language-server"] = "spectral",
  sqlls = "sqlls",
  sqls = "sqls",
  standardrb = "standardrb",
  ["starlark-rust"] = "starlark_rust",
  starpls = "starpls",
  steep = "steep",
  ["stimulus-language-server"] = "stimulus_ls",
  ["stylelint-lsp"] = "stylelint_lsp",
  superhtml = "superhtml",
  ["svelte-language-server"] = "svelte",
  svlangserver = "svlangserver",
  svls = "svls",
  ["swift-mesonlsp"] = "swift_mesonls",
  ["systemd-language-server"] = "systemd_ls",
  ["tailwindcss-language-server"] = "tailwindcss",
  taplo = "taplo",
  ["teal-language-server"] = "teal_ls",
  templ = "templ",
  ["terraform-ls"] = "terraformls",
  texlab = "texlab",
  textlsp = "textlsp",
  tflint = "tflint",
  thriftls = "thriftls",
  tinymist = "tinymist",
  ts_query_ls = "ts_query_ls",
  ["tsp-server"] = "tsp_server",
  ["twiggy-language-server"] = "twiggy_language_server",
  ["typescript-language-server"] = "ts_ls",
  ["typos-lsp"] = "typos_lsp",
  ["unocss-language-server"] = "unocss",
  ["v-analyzer"] = "v_analyzer",
  vacuum = "vacuum",
  ["vala-language-server"] = "vala_ls",
  ["vale-ls"] = "vale_ls",
  verible = "verible",
  ["veryl-ls"] = "veryl_ls",
  ["vetur-vls"] = "vuels",
  ["vim-language-server"] = "vimls",
  ["visualforce-language-server"] = "visualforce_ls",
  vls = "vls",
  ["vscode-solidity-server"] = "solidity_ls",
  vtsls = "vtsls",
  ["vue-language-server"] = "vue_ls",
  ["wgsl-analyzer"] = "wgsl_analyzer",
  ["yaml-language-server"] = "yamlls",
  zk = "zk",
  zls = "zls",
}

return M
